backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow
media_folder: "src/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Homepage"
        file: "src/index.md"
        create: false
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/home.html"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "SEO Meta Description", name: "metaDesc", widget: "string", required: false}
          - {label: "Featured Image", name: "featureImage", widget: "image", required: false}
          - {label: "Featured Image Caption", name: "featureImageCaption", widget: "string", required: false}
          - {label: "Main Content", name: "main", widget: "markdown", required: false}
          - {label: "Quote", name: "quote", widget: "text", required: false}
      - name: "about"
        label: "About"
        file: "src/about.md"
        create: false
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/about.html"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/about/"}
          - {label: "SEO Meta Description", name: "metaDesc", widget: "string", required: false}
          - {label: "Featured Image", name: "featureImage", widget: "image", required: false}
          - {label: "Featured Image Caption", name: "featureImageCaption", widget: "string", required: false}
          - {label: "Lead Intro", name: "lede", widget: "markdown", required: false}
          - {label: "Main Content", name: "main", widget: "markdown", required: false}
          - {label: "Sidebar Content", name: "aside", widget: "markdown", required: false}
      - name: "contact"
        label: "Contact"
        file: "src/contact.md"
        create: false
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/contact.html"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/contact/"}
          - {label: "SEO Meta Description", name: "metaDesc", widget: "string", required: false}
          - {label: "Featured Image", name: "featureImage", widget: "image", required: false}
          - {label: "Featured Image Caption", name: "featureImageCaption", widget: "string", required: false}
          - {label: "Lead Intro", name: "lede", widget: "markdown", required: false}
          - {label: "Sidebar Content", name: "aside", widget: "markdown", required: false}
      - name: "news-index"
        label: "News Index"
        file: "src/news.md"
        create: false
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/feed.html"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "SEO Meta Description", name: "metaDesc", widget: "string", required: false}
          - {label: "Lead Intro", name: "lede", widget: "markdown", required: false}
      - name: "projects-index"
        label: "Projects Index"
        file: "src/projects.md"
        create: false
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/projects.html"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/projects/"}
          - {label: "Lead Intro", name: "lede", widget: "markdown", required: false}
      - name: "services-index"
        label: "Services Index"
        file: "src/services.md"
        create: false
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/services.html"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/services/"}
          - {label: "Lead Intro", name: "lede", widget: "markdown", required: false}
          - {label: "Main Content", name: "main", widget: "markdown", required: false}
          - {label: "Body", name: "body", widget: "markdown", required: false}
      - name: "process"
        label: "Process"
        file: "src/process.md"
        create: false
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/process.html"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/process/"}
          - {label: "Lead Intro", name: "lede", widget: "markdown", required: false}
          - {label: "Main Content", name: "main", widget: "markdown", required: false}

  - name: "news"
    label: "News"
    label_singular: "News Post"
    folder: "src/posts"
    create: true
    slug: "{{slug}}"
    preview_path: "news/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "postAuthor", widget: "string"}
      - {label: "Publish Date", name: "postDate", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Summary", name: "postSummary", widget: "text"}
      - label: "Categories"
        name: "postCategories"
        widget: "list"
        allow_add: true
      - label: "Tags"
        name: "postTags"
        widget: "list"
        allow_add: true
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "projects"
    label: "Projects"
    label_singular: "Project"
    folder: "src/projects"
    create: true
    slug: "{{slug}}"
    preview_path: "projects/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Activities", name: "activities", widget: "string", required: false}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Client", name: "client", widget: "string", required: false}
      - {label: "Partners", name: "partners", widget: "string", required: false}
      - {label: "Service", name: "service", widget: "string", required: false}
      - {label: "Date / Year", name: "date", widget: "string", required: false}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/project.html"}
      - {label: "Location", name: "location", widget: "string", required: false}
      - {label: "Tags (comma-separated)", name: "tags", widget: "string", required: false}
      - {label: "Thumbnail", name: "thumbnail", widget: "image", required: false}
      - {label: "Summary", name: "summary", widget: "text", required: false}
      - {label: "Aside", name: "aside", widget: "markdown", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}

  - name: "services"
    label: "Services"
    label_singular: "Service"
    folder: "src/services"
    create: true
    slug: "{{slug}}"
    preview_path: "services/{{slug}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Summary", name: "summary", widget: "text", required: false}
      - {label: "Image", name: "image", widget: "image", required: false}
      - label: "Eleventy Computed"
        name: "eleventyComputed"
        widget: "object"
        required: false
        collapsed: true
        fields:
          - {label: "Title", name: "title", widget: "string", required: false, default: "{{ name }}"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/service.html"}
      - {label: "Lead Intro", name: "lede", widget: "markdown", required: false}
      - {label: "Aside 1", name: "aside1", widget: "markdown", required: false}
      - {label: "Aside 2", name: "aside2", widget: "markdown", required: false}
      - {label: "Blockquote", name: "blockquote", widget: "markdown", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}

  - name: "team-members"
    label: "Team Members"
    label_singular: "Team Member"
    folder: "src/team"
    create: true
    slug: "{{slug}}"
    preview_path: "team/{{slug}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Role", name: "role", widget: "string", required: false}
      - {label: "Location", name: "location", widget: "string", required: false}
      - {label: "Email", name: "email", widget: "string", required: false}
      - {label: "Website URL", name: "url", widget: "string", required: false}
      - {label: "LinkedIn URL", name: "linkedin", widget: "string", required: false}
      - {label: "Qualifications", name: "qualifications", widget: "string", required: false}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/member.html"}
      - {label: "Summary", name: "summary", widget: "text", required: false}

  - label: "Globals"
    name: "globals"
    files:
      - label: "Site Data"
        name: "site-data"
        file: "src/_data/site.json"
        delete: false
        fields:
          - {label: "Site Name", name: "name", widget: "string"}
          - {label: "Site URL Fallback", name: "url", widget: "string"}
          - {label: "Author Name", name: "authorName", widget: "string"}
          - {label: "Author Email", name: "authorEmail", widget: "string"}
          - {label: "Telephone", name: "telephone", widget: "string", required: false}
          - {label: "Email", name: "email", widget: "string", required: false}
          - {label: "Site ID", name: "siteID", widget: "string"}
      - label: "Main Navigation"
        name: "main-navigation"
        file: "src/_data/navigation.json"
        delete: false
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - {label: "Text", name: "text", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}
      - label: "Footer Navigation"
        name: "footer-navigation"
        file: "src/_data/footer_navigation.json"
        delete: false
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - {label: "Text", name: "text", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}
